sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t lhs009/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true lhs009/react-test-app npm test

after_success:
  - docker build -t lhs009/docker-frontend ./frontend
  - docker build -t lhs009/docker-backend ./backend
  - docker build -t lhs009/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push lhs009/docker-frontend
  - docker push lhs009/docker-backend
  - docker push lhs009/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "DockerFullstackApp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-210091168517
  bucket_path: "docker-fullstack-app"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY